### ISSUE TITLE
部分项目使用了 as-need 参数 break 了部分连接器

### ISSUE THREAD

**Issue by Rabenda** [linuxdeepin/developer-center#3345]
### SUMMARY | 问题概要

部分项目使用了 as-need 参数 break 了部分连接器 - 例如mold

使用的项目如下：

- [x] [deepin-log-viewer](https://github.com/linuxdeepin/deepin-log-viewer/blob/022f63ff38741c349559001039f8cf32e1dc03f0/application/CMakeLists.txt#L40) https://github.com/linuxdeepin/deepin-log-viewer/pull/53
- [x] [deepin-terminal](https://github.com/linuxdeepin/deepin-terminal/blob/e6281a199273794252d291e81370921e278f7fdf/CMakeLists.txt#L46) https://github.com/linuxdeepin/deepin-terminal/pull/211
- [x] [dde-session-shell](https://github.com/linuxdeepin/dde-session-shell/blob/379ed5bc9f6eb8e54a79e773acf9605e4a463a9b/CMakeLists.txt#L8) https://github.com/linuxdeepin/dde-session-shell/pull/101
- [x] [dde-control-center](https://github.com/linuxdeepin/dde-control-center/blob/2dbbe3e203191cd9ff3d79e11654492496bcbfff/src/frame/CMakeLists.txt#L12) https://github.com/linuxdeepin/dde-control-center/pull/996
- [x] [deepin-movie-reborn](https://github.com/linuxdeepin/deepin-movie-reborn/blob/15c26a138a505dc9124f9f8fb6b3bbbfbb8c8f25/src/CMakeLists.txt#L98) https://github.com/linuxdeepin/deepin-movie-reborn/pull/168
- [x] [deepin-font-manager](https://github.com/linuxdeepin/deepin-font-manager/blob/71bd3fc4baa88d87b67b2752316bf7307572fb05/deepin-font-manager/CMakeLists.txt#L41) https://github.com/linuxdeepin/deepin-font-manager/pull/83
- [x] deepin-camera https://github.com/linuxdeepin/deepin-camera/pull/208
- [x] dde-introduction  https://github.com/linuxdeepin/dde-introduction/pull/18
- [x] deepin-devicemanager https://github.com/linuxdeepin/deepin-devicemanager/pull/62
- [x] dde-file-manager https://github.com/linuxdeepin/dde-file-manager/pull/594

### STEPS TO REPRODUCE | 复现步骤

使用mold linker会报无法识别

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Gentoo

**Comment by BLumia** [comment]
相关：这个是不是后续各个项目应该改用 `add_link_options()` 或者 `target_link_options()` ，并且使用 `LINKER:` 前缀会更合适一些？

**Comment by wineee** [comment]
文管也有 https://github.com/linuxdeepin/dde-file-manager/blob/2fa523a00b7e5a7f267356fdf34235bfc8813e78/src/common/common.pri#L74

**Comment by wineee** [comment]
还有的 https://github.com/linuxdeepin/dde-grand-search/blob/e2e6142dcac9242e933b3bf40b0844bd5889d6fa/CMakeLists.txt#L17
