### ISSUE TITLE
dde 源码中硬编码路径问题

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3374]
### SUMMARY | 问题概要

# 可执行程序（改用QStandardPaths::findExecutable()

qt5integration
- [x] https://github.com/linuxdeepin/qt5integration/pull/109

deepin-screen-recorder
- [x] https://github.com/linuxdeepin/deepin-screen-recorder/blob/master/src/main_window.cpp#L2811
- [x] https://github.com/linuxdeepin/deepin-screen-recorder/pull/207
- [ ] https://github.com/linuxdeepin/deepin-screen-recorder/pull/227

deepin-downloader
- [x] https://github.com/linuxdeepin/deepin-downloader/pull/27

dde-network-core
- [x] https://github.com/linuxdeepin/dde-network-core/pull/56

dde-session-shell
- [x] https://github.com/linuxdeepin/dde-session-shell/pull/127
- [ ] https://github.com/linuxdeepin/dde-session-shell/pull/163

dde-file-manager
- [x] https://github.com/linuxdeepin/dde-file-manager/blob/787d629e2ef44efe2d68ca56bf95bd8fb5457c03/src/dde-file-manager-lib/shutil/fileutils.cpp#L1183
- [x] https://github.com/linuxdeepin/dde-file-manager/pull/580

dde-dock
- [ ] https://github.com/linuxdeepin/dde-dock/blob/689a2738109479a159fc816d355c00f4806e2f5c/plugins/overlay-warning/overlay-warning-plugin.cpp#L195
- [ ] https://github.com/linuxdeepin/dde-dock/blob/689a2738109479a159fc816d355c00f4806e2f5c/plugins/overlay-warning/com.deepin.dde.dock.overlay.policy#L16

deepin-log-viewer
- [ ] https://github.com/linuxdeepin/deepin-log-viewer/blob/613ff058cedb55e78d609d44164e4ccfc5ce762b/logViewerService/logviewerservice.cpp#L33

dde-calendar
- [ ] https://github.com/linuxdeepin/dde-calendar/blob/bb73fe191560662741da98096c133d13f847acee/calendar-service/src/csystemdtimercontrol.cpp#L110
- [ ] https://github.com/linuxdeepin/dde-calendar/blob/bb73fe191560662741da98096c133d13f847acee/calendar-service/src/csystemdtimercontrol.cpp#L127
- [ ] https://github.com/linuxdeepin/dde-calendar/blob/bb73fe191560662741da98096c133d13f847acee/calendar-service/src/jobremindmanager.cpp#L95

deepin-system-monitor
- [ ] https://github.com/linuxdeepin/deepin-system-monitor/blob/5296f81344b0cdf3eca52242c89970f91700b896/deepin-system-monitor-main/process/process_controller.cpp#L28
- [ ] https://github.com/linuxdeepin/deepin-system-monitor/blob/5296f81344b0cdf3eca52242c89970f91700b896/deepin-system-monitor-main/process/priority_controller.cpp#L28
- [ ] https://github.com/linuxdeepin/deepin-system-monitor/blob/5296f81344b0cdf3eca52242c89970f91700b896/deepin-system-monitor-main/common/common.cpp#L258
- [ ] https://github.com/linuxdeepin/deepin-system-monitor/blob/5296f81344b0cdf3eca52242c89970f91700b896/deepin-system-monitor-plugin/gui/monitor_plugin.cpp#L167

dde-introduction
- https://github.com/linuxdeepin/dde-introduction/blob/43cd3f4fe76dad84edac291ebd601df848b73cc1/src/mainwindow.h#L59

# /usr/share
- [ ] https://github.com/linuxdeepin/deepin-downloader/blob/1809f4aaea0af97c05102c4c379a71fdea0043a9/src/include/database/database.h#L22 
- [ ] https://github.com/linuxdeepin/deepin-voice-note/blob/6273c8b076219591aad08645653fb48ef8a2bc57/src/common/audiowatcher.cpp#L387  watcherConfigFilePaths 应该读XDG_DATA_DIRS 比较好

**Comment by wineee** [comment]
QProcess::startDetached("/usr/lib/deepin-daemon/desktop-toggle") 这种 PATH 里找不到的怎么办

**Comment by BLumia** [comment]
> QProcess::startDetached("/usr/lib/deepin-daemon/desktop-toggle") 这种 PATH 里找不到的怎么办

CMakeLists 里加选项定义，或者加宏然后在代码里用宏里定义的路径？

**Comment by wineee** [comment]
在 NixOS 中，需要在 dtkwidget 有这样一个 patch
https://github.com/linuxdeepin/dde-nixos/blob/c11a1c1e99dace103fabc555a218b0b8d1e1f3c4/packages/library/dtkwidget/default.nix#L64

wrap-qt-apps-hook 只检查软件本身的 share 目录，不检查依赖的，而依赖dtkwidget只是库，不是可执行程序，不会被 warp
https://github.com/NixOS/nixpkgs/blob/690f9aef3c3d1b0b810fd57df3bb4fe0cca3e56a/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh#L53

似乎没有更好的办法

**Comment by wineee** [comment]
Thanks @DonaldKellett, make lots of contributions

**Comment by BLumia** [comment]
Hi @DonaldKellett, just FYI you can update existing PR by simply pushing new commit(s) to the branch that you used to create the PR, so you will no longer need to close and create a new PR every time you want to modify/amend a PR :)

**Comment by DonaldKellett** [comment]
> Hi @DonaldKellett, just FYI you can update existing PR by simply pushing new commit(s) to the branch that you used to create the PR, so you will no longer need to close and create a new PR every time you want to modify/amend a PR :)

Noted with thanks :smile:
