### ISSUE TITLE
解决插件/组件路径硬编码的倡议

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#3402]
### SUMMARY | 问题概要

部分软件导入插件使用了硬编码路径，降低了可移植性
（补充一下：我不是想 3 选 1, 而是这 3 个尽量都加上）

### 1. 对插件使用变量指定安装路径

比如 

deepin-compressor  COMPRESSOR_PLUGIN_PATH

dde-session-shell  SESSION_SHELL_MODULE_PATH

dde-dock DOCK_PLUGIN_PATH 和 DOCK_TRAYS_PLUGIN_PATH

默认值应该使用 CMAKE_INSTALL_LIBDIR 作为前缀，而不是 /usr/lib/…
有需要不遵守GNUInstallDirs的自行编译时用 -DCOMPRESSOR_PLUGIN_PATH=... 设置

在 config.h.in 中添加 

```
#define COMPRESSOR_PLUGIN_PATH "@COMPRESSOR_PLUGIN_PATH@"
```

camke 使用 configure_file 进行替换

```
configure_file(config.h.in config.h @ONLY)
```

源码中使用 COMPRESSOR_PLUGIN_PATH 宏作为插件路径

### 2. 读取环境变量

对 deepin 本身， 1 应该足够了。不过从环境变量对取插件路径会更灵活。至少，在 NixOS 中，比如有些 dde-dock 的插件是其他项目提供的(比如dde-grand-search)，这些项目编译时依赖 dde-dock，而 DOCK_PLUGIN_PATH 在编译 dock 时就已经确定，就不能读其他项目的 dock 插件了。（在 NixOS 中，dock的dcok插件和dde-grand-search的dock插件不能安装在同一目录，即使用symbolJob链接进同一目录，新目录的位置已经不是DOCK_PLUGIN_PATH了，需要环境变量来确定）

这个可以作为可选项，可以增加 READ_PLUGIN_PATH_FROM_ENV 的编译选项可选支持。默认不启用。有需求是用户或开发者自行启用。环境变量的设置也由有需求是用户/开发者负责。

环境变量命名类似：

D_COMPRESSOR_PLUGIN_DIR(S)
D_SESSION_SHELL_MODULE_DIR(S)
D_DOCK_PLUGIN_DIR(S) 
D_DOCK_TRAYS_PLUGIN_DIR(S)

只支持单路径用 DIR，支持多个路径用 DIRS

应该尽可能支持多个路径比较好？

### 3. 绿色运行

指直接解压 deb 包/直接编译没有 install 就可以运行。这种应该根据相对路径来找插件。
dde-dock 实际已经做了 https://github.com/linuxdeepin/dde-dock/blob/02ffb8ad491d75c605ff49d1aa450ae4d2c5a8ae/plugins/tray/system-trays/systemtrayscontroller.cpp?rgh-link-date=2022-09-01T06%3A32%3A04Z#L169

deepin-compressor 是不是也应该加上

### 涉及项目

[deepin-compressor](https://github.com/linuxdeepin/deepin-compressor)

- [ ]  [https://github.com/linuxdeepin/deepin-compressor/blob/master/src/source/common/pluginmanager.cpp#L255-L256](https://github.com/linuxdeepin/deepin-compressor/blob/master/src/source/common/pluginmanager.cpp#L255-L256)

dde-session-shell

- [ ]  [https://github.com/linuxdeepin/dde-session-shell/blob/255c191d8d48a2042abae748f3927677d8e7f5a0/src/global_util/modules_loader.cpp#L20](https://github.com/linuxdeepin/dde-session-shell/blob/255c191d8d48a2042abae748f3927677d8e7f5a0/src/global_util/modules_loader.cpp#L20)

dde-dock

- [ ]  [https://github.com/linuxdeepin/dde-dock/blob/master/plugins/tray/system-trays/systemtrayscontroller.cpp#L171](https://github.com/linuxdeepin/dde-dock/blob/master/plugins/tray/system-trays/systemtrayscontroller.cpp#L171)

dde-clipboard

- [ ]  [https://github.com/linuxdeepin/dde-clipboard/blob/1ae05cd8004d7da29343095140c6983fe27795c0/dde-clipboard-daemon/dbus_manager.cpp#L271](https://github.com/linuxdeepin/dde-clipboard/blob/1ae05cd8004d7da29343095140c6983fe27795c0/dde-clipboard-daemon/dbus_manager.cpp#L271)

dde-polkit-agent

相关 pr [https://github.com/linuxdeepin/dde-polkit-agent/pull/12](https://github.com/linuxdeepin/dde-polkit-agent/pull/12)

dde-control-center

- [ ] [https://github.com/linuxdeepin/dde-control-center/blob/ba3bb2b3395ce21280300a4b75ca6fe34465e2e2/src/frame/window/mainwindow.cpp#L69](https://github.com/linuxdeepin/dde-control-center/blob/ba3bb2b3395ce21280300a4b75ca6fe34465e2e2/src/frame/window/mainwindow.cpp#L69)
- [ ] [https://github.com/linuxdeepin/dde-control-center/blob/ba3bb2b3395ce21280300a4b75ca6fe34465e2e2/src/frame/window/insertplugin.cpp#L11](https://github.com/linuxdeepin/dde-control-center/blob/ba3bb2b3395ce21280300a4b75ca6fe34465e2e2/src/frame/window/insertplugin.cpp#L11)

是 https://github.com/linuxdeepin/developer-center/issues/3374 的一部分

**Comment by BLumia** [comment]
1 本身没什么问题。
2 要解决的问题，其实应该以和 1 一样的方式来做吧。比如 1 中配置了头文件设置了路径，那么如果这些路径别的项目也用得到的话，这个头文件本身也应该暴漏给别的项目。当然别的形式也可以，比如暴漏 CMake 模块之类的方式
3...好像没这个必要？很多时候你构建的代码本身也不是位置无关的，真的要做绿色运行感觉不如直接考虑 AppImage 支持

（一点看法，不一定对

**Comment by wineee** [comment]
2. 我提出 2 本身是为了 NixOS 等特殊的情况，至少，在 NixOS 中即使知道 dde-dock 项目本身插件安装进哪了，编译dde-grand-search时根本不能动那个目录（/nix/store/*****hashvar****dde-dock-version/lib/dde-dock/plugin/）。Nix 某个软件目录都是不一样的

4. 本来就不是必要，只是加上会不会更好

**Comment by BLumia** [comment]
3 要总是能同时确保构建出位置无关可执行才有意义。
2 本身也不需要动对应的目录，只是需要他们能有个一致的位置放置插件，比如其它程序把生成的 dock 插件安装到 `/nix/store/*****hashvar****dde-dock-version/lib/dde-dock/plugin/` 下，这个可以做到吗？

**Comment by wineee** [comment]
> 2 本身也不需要动对应的目录，只是需要他们能有个一致的位置放置插件，比如其它程序把生成的 dock 插件安装到 `/nix/store/*****hashvar****dde-dock-version/lib/dde-dock/plugin/` 下，这个可以做到吗？

无法做到，dock程序的目录只有构建dock的时候nix daemon有权限改。除非把dde-grand-search作为dock的构建依赖，在构建的时候把插件放一起。 可是 dock 是 dde-grand-search 的构建依赖

**Comment by wineee** [comment]
不过还有一个办法，在 nixos 的 dde 模块设置 environment.pathsToLink，加上 "/lib/dde-dock/plugins"，这样只要是 environment.systemPackages 里的软件有 ${package-path}/lib/dde-dock/plugins 这样的目录，都会软链接到 system-path（/run/current-system/sw/） ，可以把插件位置设置成这个路径。

缺点：
nix 仍然需要 patch 自己一下 config.h.in，不过可以接受
nix 本身可在其他 linux 系统使用，这样只适配 NixOS， dock倒是无所谓，compressor等是不是用更通用的方法好

**Comment by ssk-wh** [comment]
qt中源码中加载插件一般就是1的做法
优先基于环境变量去获取插件的路径，然后为空，则缺省指定一个
