### ISSUE TITLE
控制中心输入法插件页面重构

### ISSUE THREAD

**Issue by zsien** [linuxdeepin/developer-center#3871]
- [x] 修改日志方式，使用 Qt 的日志 linuxdeepin/deepin-fcitx5configtool-plugin#4
- [x] 重构输入法主页面 linuxdeepin/deepin-fcitx5configtool-plugin#6
   - [x] 使用 dcc-widgets，并删除与之重复的自定义 widgets
   - [x] 将已添加输入法列表改为使用 DListView
   - [x] 使用 QAction 重写已添加输入法项操作
- [x] 重构添加输入法页面 linuxdeepin/deepin-fcitx5configtool-plugin#11
  - [x] 删除自行绘制的页面样式，改为使用 DTK
  - [x] 使用 DListView 的 rootIndex 实现子列表
  - [x] 删除原本的 delegate，尽量使用 DTK 来实现列表样式
  - [x] 新增 delegate，将输入法分类的 selected 样式改为 checked 样式
  - [x] 删除无用的刷新列表，修复打开输入法模块缓慢
  - [x] 修改输入法分类逻辑
  - [x] 修改列表排序逻辑，不特化中文 locale 下的排序
  - [x] 置顶含有支持当前语言的输入法的分类
  - [x] 修复点击添加输入法按钮会弹出三个窗口
- [x] 完善列表排序逻辑（修改重构后不符合需求部分） linuxdeepin/deepin-fcitx5configtool-plugin#13
  - [x] 将包含已添加输入法的分类置顶
  - [x] 将已经添加的输入法置顶，并且不可选择
  - [x] 默认选择每个分类下第一个未被添加的输入法
- [x] 使用 ToolTip 显示当前完整输入法名称 linuxdeepin/deepin-fcitx5configtool-plugin#14
- [x] 重写键盘布局图案绘制 linuxdeepin/deepin-fcitx5configtool-plugin#17

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0425镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230425
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过
