### ISSUE TITLE
DDE v23 3/28~29 统一 tag 与集成进度跟进

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#3941]
本次统一 tag 涉及开源社区中心所维护的所有 DDE 组件，旨在解决两个问题：

1. 鉴于 alpha2 版本使用的 tag 与 GitHub 同步出来的 tag 可能不一致，此次统一进行一次 tag release，以确保接手并移至 GitHub 开发后，各个项目有一个可构建的、可靠的新 tag 版本。
2. 在 alpha2 到 beta 过程中存在部分影响性可能较大的变动，在此次统一 tag 后以便排查确认这些问题是否存在。这些变动分别是
   1. 桌面环境名称对应的那个环境变量的值从 Deepin 改到 DDE（ https://github.com/linuxdeepin/developer-center/issues/3829 ），部分组件可能仍在判断这个值
   2. dde-api-proxy 那个兼容旧 dbus 的服务不会再预装到 v23 环境中（已经装了的不会主动卸载，但建议手动卸载它来测试是否有问题）

故请 DDE 维护人员在今、明两日对所维护的项目以更新 changelog 的形式进行一次 tag release（alpha2 后无任何变动的 DDE 项目也需要进行一次 tag release）。

另外，提交集成前，请：

1. Review 并合并 OBS 工作流配置的相关 PR，参见： https://github.com/linuxdeepin/developer-center/issues/3931
2. 检查是否需要拉取翻译，并视情况更新翻译

@dengbo11 

- [x] go-lib https://github.com/linuxdeepin/go-lib/pull/89
- [x] dde-api https://github.com/linuxdeepin/dde-api/pull/89
- [x] go-gir-generator https://github.com/linuxdeepin/go-gir-generator/pull/36
- [x] go-gir 该项目由go-gir-generator替代, 后面将废弃, 故无需tag
- [x] dde-session https://github.com/linuxdeepin/dde-session/pull/12
- [x] dde-appearance https://github.com/linuxdeepin/dde-appearance/pull/18
- [x] dde-display 未达到发布标准，且无其他组件在依赖此项目，本次无需 tag
- [x] go-dbus-factory https://github.com/linuxdeepin/go-dbus-factory/pull/94
- [x] dde-account-faces https://github.com/linuxdeepin/dde-account-faces/pull/26

@zsien 

- [x] dde-daemon linuxdeepin/dde-daemon#488
- [x] startdde linuxdeepin/startdde#216
- [x] dde-cooperation linuxdeepin/dde-cooperation#5
- [x] ~~dde-api-proxy~~ 不再集成新版本。若仍需此项目的 tag 请另外联系我们。
- [x] deepin-fcitx5configtool-plugin linuxdeepin/deepin-fcitx5configtool-plugin#21
- [x] dde-application-manager linuxdeepin/dde-application-manager#16

@Decodetalkers 

- [x] dde-control-center linuxdeepin/dde-control-center#1253
- [ ] xdg-desktop-portal-dde

@18202781743 

- [x] dde-widgets https://github.com/linuxdeepin/dde-widgets/pull/35
- [x] dde-network-core https://github.com/linuxdeepin/dde-network-core/pull/146
- [x] dde-app-services https://github.com/linuxdeepin/dde-app-services/pull/43

@l631197874 

- [x] go-x11-client https://github.com/linuxdeepin/go-x11-client/pull/30
- [x] dde-polkit-agent https://github.com/linuxdeepin/dde-polkit-agent/pull/148

@BLumia 

- [x] dde-launcher https://github.com/linuxdeepin/dde-launcher/pull/383
- [x] dde-session-ui https://github.com/linuxdeepin/dde-session-ui/pull/330

@tsic404 

- [x] dde-dock https://github.com/linuxdeepin/dde-dock/pull/814

@asterwyx 

- [x] dde-session-shell https://github.com/linuxdeepin/dde-session-shell/pull/313

其他：

- [x] deepin-icon-theme https://github.com/linuxdeepin/deepin-icon-theme/pull/61
- [x] deepin-desktop-theme https://github.com/linuxdeepin/deepin-desktop-theme/pull/8
- [ ] dde-qt-dbus-factory
- [x] dde-clipboard https://github.com/linuxdeepin/dde-clipboard/pull/129

**Comment by BLumia** [comment]
请将更新 changelog 的 PR 以编辑描述的形式贴到此 Issue 的描述中。

上述列表中，若有遗漏的项目或与实际不服的情况，也请直接编辑或回复告知，以便及时更正/更新内容。

**Comment by BLumia** [comment]
所涉及的必要项目均已提交集成，此 Issue 进行关闭。

注意：

1. 此 Issue 未跟进 DTK 以及平台插件的版本，但 DTK 与平台插件也需要更新，可参考 https://github.com/linuxdeepin/developer-center/issues/3829 。
2. 此 Issue 记录的统一集成所使用的版本不一定与 beta 发布时使用的版本一致，若有高于本次列出的 tag 版本的版本，则请考虑使用新 tag。beta 发布时也会存在一个 beta 版本所使用的软件包的完整 tag 列表，届时也可参考对应的列表清单。
