### ISSUE TITLE
部分项目编译参数有拼写错误： D_FORTITY_SOURCE -> D_FORTIFY_SOURCE 且不应在 cmake 设置

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/developer-center#4292]
### SUMMARY | 问题概要

根本不存在 D_FORTITY_SOURCE 这个参数，正确写法是 D_FORTIFY_SOURCE https://www.redhat.com/en/blog/security-technologies-fortifysource

upd： 

此参数建议有打包者配置而非 cmake： https://github.com/orgs/linuxdeepin/discussions/4301

- [x] https://github.com/linuxdeepin/dde-control-center/pull/1328
- [x] dde-calendar https://github.com/linuxdeepin/dde-calendar/pull/150
- [ ] deepin-reader
- [ ] dde-printer
- [ ] docparser
- [ ] dtkcommon
- [ ] deepin-pdfium
- [ ] dde-qt-dbus-factory
- [ ] deepin-manual
- [ ] dde-session-ui
- [ ] deepin-devicemanager
- [ ] deepin-font-manager
- [ ] deepin-compressor
- [ ] deepin-deb-installer
- [ ] deepin-voice-note
- [ ] dde-network-core
- [ ] deepin-terminal

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
master
```

### STEPS TO REPRODUCE | 复现步骤

none

**Comment by Decodetalkers** [comment]
改了后会产生巨大多的编译警告诶。。干脆去掉吧

**Comment by wineee** [comment]
fority 用于检查是否存在缓冲区溢出的错误, 应该优先规范代码来符合检查， 这个参数打包也常用

**Comment by Decodetalkers** [comment]
> fority 用于检查是否存在缓冲区溢出的错误, 应该优先规范代码来符合检查， 这个参数打包也常用

![image](https://user-images.githubusercontent.com/60290287/236746620-06b07d9c-756b-4d73-af07-198a8facc8a9.png)
现在会变成这个样子。我想没有用对

**Comment by wineee** [comment]
这个和 @xzl01 遇到的问题一样了，我们的 glibc 没有打 patch

**Comment by wineee** [comment]
https://github.com/deepin-community/glibc/pull/2 已经合并了

**Comment by BLumia** [comment]
- 关联讨论： https://github.com/linuxdeepin/developer-center/discussions/4301

这个参数（以及一些别的类如优化级别的参数）不应该在 CMakeLists 里硬编码，应当由发行版提供默认的参数供所有包使用，若需覆盖时应当修改 debian/rules 进行覆盖而不是在 CMakeLists 中覆盖。
