### ISSUE TITLE
实习任务(打包维护)-字体包移植

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4792]
任务需求： 移植其他开源社区的字体包到deepin v23中
完成标准：  通过CI/CD检查，代码合入仓库
字体包来源： 
```[tasklist]
### Tasks
- [ ] 霞鹜文楷 https://github.com/lxgw/LxgwWenKai
- [ ] intel-one-mono https://github.com/intel/intel-one-mono
- [ ] firacode https://github.com/tonsky/FiraCode
- [ ] google-noto https://fonts.google.com/noto
- [ ] hack https://sourcefoundry.org/hack/
```

**Comment by Rabenda** [comment]
这个任务需要同时评估一下内容：
是否可重分发
如果默认不许重分发 需要去请求对应重分发授权
