### ISSUE TITLE
实习任务(打包维护)-流行软件包移植

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/developer-center#4794]
任务需求： 移植具有一定流行度的软件包到deepin 23中
完成标准： 通过CI/CD检查，PR合入仓库
任务补充： 参照软件包统计表移植deepin 23中没有的软件包到https://github.com/deepin-community  尽量选取排名靠前的软件包
软件包统计表:  https://popcon.debian.org/by_inst
相比与debian仓库deepin仓库中缺少的软件包:  https://ci.deepin.com/repo/deepin/deepin-ports/deb/pkg-list.txt
```[tasklist]
### Tasks
- [ ] wofi
- [ ] rofi
```

**Comment by Zeno-sole** [comment]
https://github.com/orgs/linuxdeepin/discussions/4799

**Comment by Zeno-sole** [comment]
https://github.com/linuxdeepin/developer-center/issues/4803

**Comment by Zeno-sole** [comment]
补充rust相关依赖包，可能会存在相互依赖问题，可以使用topic解决(参见wiki 搜索相关词条)

- [ ] librust-memchr-dev
- [ ] librust-aho-corasick-dev
- [ ] librust-aho-corasick+std-dev
- [ ] librust-winapi-i686-pc-windows-gnu-dev
- [ ] librust-winapi-x86-64-pc-windows-gnu-dev
- [ ] librust-winapi-dev
- [ ] librust-ansi-term-dev
- [ ] librust-libc-dev
- [ ] librust-atty-dev
- [ ] librust-bitflags-dev
- [ ] librust-version-check-dev
- [ ] librust-nom-dev
- [ ] librust-nom+std-dev
- [ ] librust-cexpr-dev
- [ ] librust-cfg-if-0.1-dev
- [ ] librust-glob-dev
- [ ] librust-clang-sys-dev
- [ ] librust-unicode-width-dev
- [ ] librust-textwrap-dev
- [ ] librust-clap-dev
- [ ] librust-clap+color-dev
- [ ] librust-strsim-dev
- [ ] librust-clap+strsim-dev
- [ ] librust-vec-map-dev
- [ ] librust-clap+default-dev
- [ ] librust-cloudabi-dev
- [ ] librust-cloudabi+default-dev
- [ ] librust-log-dev
- [ ] librust-env-logger-dev
- [ ] librust-humantime-dev
- [ ] librust-regex-syntax-dev
- [ ] librust-regex-dev
- [ ] librust-scopeguard-dev
- [ ] librust-lock-api-dev
- [ ] librust-redox-syscall-dev
- [ ] librust-smallvec-dev
- [ ] librust-parking-lot-core-dev
- [ ] librust-parking-lot-dev
- [ ] librust-once-cell-dev
- [ ] librust-thread-local-dev
- [ ] librust-regex+perf-cache-dev
- [ ] librust-regex+perf-literal-dev
- [ ] librust-regex+perf-dev
- [ ] librust-winapi-util-dev
- [ ] librust-termcolor-dev
- [ ] librust-env-logger+default-dev
- [ ] librust-lazy-static-dev
- [ ] librust-lazycell-dev
- [ ] librust-peeking-take-while-dev
- [ ] librust-unicode-xid-dev
- [ ] librust-proc-macro2-dev
- [ ] librust-quote-dev
- [ ] librust-regex+unicode-age-dev
- [ ] librust-regex+unicode-bool-dev
- [ ] librust-regex+unicode-case-dev
- [ ] librust-regex+unicode-gencat-dev
- [ ] librust-regex+unicode-perl-dev
- [ ] librust-regex+unicode-script-dev
- [ ] librust-regex+unicode-segment-dev
- [ ] librust-regex-syntax+unicode-dev
- [ ] librust-regex+unicode-dev
- [ ] librust-rustc-hash-dev
- [ ] librust-shlex-dev
- [ ] librust-which-dev
