### ISSUE TITLE
【deepin_V23_beta3】【持续更新】【软件与应用包集成单专用】【内测反馈集合贴】【版本需求集合贴】用于beta3版本应用软件集成单（主要进行开源软件的打包）

### ISSUE THREAD

**Issue by kobe337** [linuxdeepin/developer-center#5718]
### SUMMARY | 问题概要

用于beta3版本应用软件集成单

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
https://cdimage.uniontech.com/community/releases/23-Beta2/
```

### STEPS TO REPRODUCE | 复现步骤

1.主要来源：用户论坛、深度之家、产品需求等

### OBSERVED RESULT | 观察到的结果

此贴专用与v23 beta3版本的所有需求与用户反馈的软件应用集合贴

### EXPECTED RESULT | 期望的结果

存在不可控的无法集成情况时，需要备注详细说明，比如：由于技术上不可解决，目前无法兼容，后续的安排等

```[tasklist]
### Tasks
- [x] goldendict
- [x] codeblocks
- [x] wireshark
- [ ] bpftrace
- [ ] remmina
- [x] cherrytree
- [x] synaptic
- [ ] Inkscape
- [ ] Krita
- [ ] Scribus
- [ ] githash
- [ ] Synergy-键鼠共享
- [x] httpie https://github.com/linuxdeepin/developer-center/issues/6664
- [x] clonezilla
- [ ] grub2 update
- [x] trimage https://github.com/linuxdeepin/developer-center/issues/6665
- [ ] xmake
- [x] cowsay
- [x] wlr-randr
- [x] seafile-gui
- [ ] apt-transport-tor
- [ ] kdiff3
- [ ] gdb-doc
```

**Comment by kobe337** [comment]
@meiyixiang 此贴专用于记录应用软件反馈与需求应用内容

**Comment by kobe337** [comment]
【用户反馈需求软件名】goldendict
【反馈来源】论坛反馈
【反馈用户】一路风尘

**Comment by xzl01** [comment]
> 【用户反馈需求软件名】goldendict 【反馈来源】论坛反馈 【反馈用户】一路风尘

https://github.com/goldendict/goldendict/  但是基于旧的qt4 不予在源内维护，反馈给应用商店，看他们是否愿意维护

**Comment by meiyixiang** [comment]
希望增加抓包软件wireshark

**Comment by meiyixiang** [comment]
求cherrytree
https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbbbd8267a1fb69b0d68b/row/9857d1fd-254f-4fa2-b347-0816869885fc 记录：求cherrytree

**Comment by meiyixiang** [comment]
求remmina
https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbbbd8267a1fb69b0d68b/row/56e94eca-47a2-4263-b620-e2d71919815f 记录：求remmina

**Comment by xzl01** [comment]
> synaptic https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbbbd8267a1fb69b0d68b/row/a10e95af-507c-417a-b38c-5f19c51dbe69 记录：V23一些基本需求问题

https://github.com/linuxdeepin/developer-center/issues/5805

**Comment by luodeepin** [comment]
> 突触 https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbbbd8267a1fb69b0d68b/row/a10e95af-507c-417a-b38c-5f19c51dbe69 记录：V23一些基本需求问题

应用 ： 新立得包管理器 0.91.3 验证通过

**Comment by kobe337** [comment]
用户反馈应用：Inkscape、Krita、Scribus
链接：https://bbs.deepin.org/post/263309?id=263309&limit=20&offset=0&postId=1524397

**Comment by wineee** [comment]
> > 【用户反馈需求软件名】goldendict 【反馈来源】论坛反馈 【反馈用户】一路风尘
> 
> [goldendict/goldendict](https://github.com/goldendict/goldendict/) 但是基于旧的qt4 不予在源内维护，反馈给应用商店，看他们是否愿意维护

基于的qt4的结论从何而来，从源码 qmake 看是支持 qt5 的，并且上游近期也在维护

**Comment by hotime** [comment]
龙芯浏览器  http://www.loongnix.cn/zh/api/lbrowser/

**Comment by meiyixiang** [comment]
bludefish
上架社区https://bluefish.openoffice.nl/index.html

**Comment by meiyixiang** [comment]
browser-plugin-freshplayer-pepperflash
【产品现状】： 仓库中没有，需要安装
【产品期望】： 希望添加

**Comment by Zeno-sole** [comment]
> browser-plugin-freshplayer-pepperflash 【产品现状】： 仓库中没有，需要安装 【产品期望】： 希望添加

Flash 相关插件已停止维护，拒绝

**Comment by meiyixiang** [comment]
希望能够支持synergy
反馈链接：https://bbs.deepin.org/zh/post/263859?id=263859&limit=20&offset=0&postId=1529323@

**Comment by xzl01** [comment]
> 希望能够支持synergy 反馈链接：https://bbs.deepin.org/zh/post/263859?id=263859&limit=20&offset=0&postId=1529323@

CC @BLumia

**Comment by xzl01** [comment]
> 龙芯浏览器 http://www.loongnix.cn/zh/api/lbrowser/

没有发现其提供的源码 无法收录

**Comment by xzl01** [comment]
> 求cherrytree https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbbbd8267a1fb69b0d68b/row/9857d1fd-254f-4fa2-b347-0816869885fc 记录：求cherrytree

https://github.com/deepin-community/cherrytree/pulls

**Comment by meiyixiang** [comment]
gnome-network-displays,实现投屏到电视
https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbbbd8267a1fb69b0d68b/row/ebf5a136-6d8e-425c-9ab0-1bf192bf7fe0 记录：建议在应用商店上架gnome-network-displays,实现投屏到电视

**Comment by meiyixiang** [comment]
【产品现状】： 23 beta2 没有
【产品期望】： 添加上virt-viewer这个包，安装kvm虚拟机的时候需要
https://packages.debian.org/search?keywords=virt-viewer

**Comment by yaoyingkeji** [comment]
【用户反馈需求软件名】:clonezilla
【产品现状】： 仓库中没有
【产品期望】： 希望添加
【deb包】：https://packages.debian.org/buster/all/clonezilla
【软件主页】：https://clonezilla.org/
【软件源码】：https://free.nchc.org.tw/drbl-core/src/
【软件截图】：
![截图_选择区域_20231120161506](https://github.com/linuxdeepin/developer-center/assets/93997433/45800816-8bb8-48d5-9ac0-fdf1710444f5)
![截图_选择区域_20231120161401](https://github.com/linuxdeepin/developer-center/assets/93997433/8cb0d0ba-5b1f-4bdf-bbd6-febe4a67454f)
![截图_选择区域_20231120160920](https://github.com/linuxdeepin/developer-center/assets/93997433/b009da70-9199-46c7-80ca-7c5725044add)

**Comment by meiyixiang** [comment]
xpadneo in repo
Biezacy status produktu : Please add to the repository for all players or better out of the box.
Oczekiwany produkt]: https://atar-axis.github.io/xpadneo/

**Comment by meiyixiang** [comment]
https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbbbd8267a1fb69b0d68b/row/f942edfd-f734-4907-8235-d6163863c1c3 记录：仓库中请求加入 httpie

**Comment by SuperEffie** [comment]
【用户反馈链接】：https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/row/df5e9171-2445-4a86-97a9-298832481fd5 
【需求】：v23仓库中请求加入python-glade2包

**Comment by SuperEffie** [comment]
【用户反馈链接】：https://cooperation.uniontech.com/app/6f20cf83-ef8a-4067-bac9-b05c6d6bbcb6/648bfccc0a1f50226a98dbc6/648fbba79d15fe3df1444e6c/row/e464d563-7659-4ca2-88bd-523f1c9a58bb
【需求】：v23仓库中请添加trimage包

**Comment by xzl01** [comment]
https://github.com/linuxdeepin/developer-center/issues/6664

**Comment by xzl01** [comment]
> 【用户反馈需求软件名】:clonezilla 【产品现状】： 仓库中没有 【产品期望】： 希望添加 【deb包】：https://packages.debian.org/buster/all/clonezilla 【软件主页】：https://clonezilla.org/ 【软件源码】：https://free.nchc.org.tw/drbl-core/src/ 【软件截图】： ![截图_选择区域_20231120161506](https://private-user-images.githubusercontent.com/93997433/284219682-45800816-8bb8-48d5-9ac0-fdf1710444f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDA0MjIsIm5iZiI6MTcwNDcwMDEyMiwicGF0aCI6Ii85Mzk5NzQzMy8yODQyMTk2ODItNDU4MDA4MTYtOGJiOC00OGQ1LTlhYzAtZmRmMTcxMDQ0NGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3NDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkN2RiN2UxY2M3MGRkYzVkZTVmYWJmYmUzMzlkNTY5MDRiODBjNzhmNTY3N2EzOGVkYjM5MmFjM2FmNGE1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VHwFr_LhXaHJyVbMJGsJndiP55J8ZzPL-VqkVDbgB28) ![截图_选择区域_20231120161401](https://private-user-images.githubusercontent.com/93997433/284219698-8cb0d0ba-5b1f-4bdf-bbd6-febe4a67454f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDA0MjIsIm5iZiI6MTcwNDcwMDEyMiwicGF0aCI6Ii85Mzk5NzQzMy8yODQyMTk2OTgtOGNiMGQwYmEtNWIxZi00YmRmLWJiZDYtZmViZTRhNjc0NTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3NDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZWRiM2E4ZWM2Yzg2ODZlMGZhYmIxYTEwM2RjNjY4N2M5Y2I0OWY5M2U1NGQ4YTdkYjNlYzE2ZWM2NDBhNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FQqiFHPfjUMTEqavgSxdg_NPchMzMHzmHf-A43nWG7Y) ![截图_选择区域_20231120160920](https://private-user-images.githubusercontent.com/93997433/284219701-b009da70-9199-46c7-80ca-7c5725044add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDA0MjIsIm5iZiI6MTcwNDcwMDEyMiwicGF0aCI6Ii85Mzk5NzQzMy8yODQyMTk3MDEtYjAwOWRhNzAtOTE5OS00NmM3LTgwY2EtN2M1NzI1MDQ0YWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3NDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYTM2YjY3MDUyMjI5YzExMTEyOGE3ZGZjZTgwYjAxMzkwYThjMjIwMDgwYzc3MjEwM2ZiNjRjMTcwYjc4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5itsON-bNXlvmmpAdGROUoOIL2s6MnTNuOVzrwrtus0)

done

**Comment by waruqi** [comment]
希望加上  xmake https://github.com/xmake-io/xmake

**Comment by wineee** [comment]
需要 wlr-randr ( wlroots base 屏幕管理
https://manpages.debian.org/testing/wlr-randr/wlr-randr.1.en.html

**Comment by Avenger-285714** [comment]
目前工作环境需要以下软件包：
一、gnome-terminal
        https://packages.debian.org/bookworm/gnome-terminal
二、gnome-console
        https://packages.debian.org/bookworm/gnome-console
三、autojump
        https://github.com/wting/autojump
        https://packages.debian.org/bookworm/autojump
四、cabextract
        https://www.cabextract.org.uk/
        https://packages.debian.org/bookworm/cabextract
五、kdiff3
        https://invent.kde.org/sdk/kdiff3
        https://packages.debian.org/bookworm/kdiff3
六、gedit-plugins
        https://packages.debian.org/bookworm/gedit-plugins
七、devhelp
        https://packages.debian.org/bookworm/devhelp
八、gdb-doc
        https://packages.debian.org/bookworm/gdb-doc
九、lolcat
        https://github.com/busyloop/lolcat
        https://packages.debian.org/bookworm/lolcat
十、xcowsay
        https://www.doof.me.uk/xcowsay/
        https://packages.debian.org/bookworm/xcowsay

另外，所有的gnome的软件包我们几乎都没有，和debian比起来差的非常之多，望尽快补齐

**Comment by Avenger-285714** [comment]
缺包：
apt-transport-tor
参考：
https://packages.debian.org/sid/apt-transport-tor
https://support.torproject.org/apt/

**Comment by Avenger-285714** [comment]
打包需求：一个现代的终端模拟器
名称：contour-terminal
参考：
https://contour-terminal.org/
https://github.com/contour-terminal/contour

原因：
1. 和wezterm比这个不依赖Rust工具链
2. deepin23仓库里面可用的终端也实在太少了吧

**Comment by kobe337** [comment]
beta3版本已经发布，此issues关闭，未集成完成的软件后续以此单进行跟踪：
https://github.com/linuxdeepin/developer-center/issues/7284

**Comment by Avenger-285714** [comment]
缺包cabextract，导致ttf-mscorefonts-installer等包缺失依赖无法安装

**Comment by Avenger-285714** [comment]
缺包：node-got，node-err-code，node-yargs，node-jest-debbundle导致无法安装npm，这东西很常用的烦请各位开发者尽快修复
