### ISSUE TITLE
【dde-launchpad】处理已知焦点切换相关问题

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#5809]
```[tasklist]
### Tasks
- [x] 小窗口 launcher 使用 tab 切换焦点到分类按钮、左侧列表项、右侧搜索框、全屏按钮、收藏的应用、所有应用列表
- [x] 全屏窗口 launcher 使用 tab 切换焦点到搜索框、小窗口按钮、所有应用列表
- [ ] https://github.com/linuxdeepin/developer-center/issues/5462
- [ ] https://github.com/linuxdeepin/developer-center/issues/5422
```
