### ISSUE TITLE
【dde-launchpad】迁移至 Qt6/DTK6

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#5931]
```[tasklist]
### Tasks
- [x] dtk6declarative 发布至少一个 tag
- [x] 提供选项屏蔽用到 appstream-qt 的功能
- [ ] https://github.com/linuxdeepin/dtk6declarative/pull/2
- [ ] https://github.com/linuxdeepin/dtk6core/pull/12
- [ ] https://github.com/linuxdeepin/dtkcore/pull/386
- [ ] https://github.com/linuxdeepin/dde-launchpad/pull/18
- [x] launchpad 本体移植到 Qt 6
```

部分原有依赖选择了暂时 vendor 或暂时提供选项禁用的方式处理，待外部依赖就绪后再改回来。外部依赖进度跟进：

- [x] ~~kitemmodels 发布至少一个 kf6 tag~~ （不再依赖 kitemmodels，也不再计划依赖 kitemmodels）
- [x] appstream-qt 发布支持 Qt 6 的 tag （已经发布）

与打包移植相关：

- [x] deepin v23 仓库 dtk6 就绪
- [x] deepin v23 仓库支持 Qt6 的 appstream-qt 就绪（阻塞：需要打包 appstream(-qt) 1.0）
- [x] Arch 仓库 dtk6 就绪 @felixonmars
- [x] Arch 仓库 kf6 就绪（注：Arch 以 5.240 打了 kf6 的 tag）
- [x] Arch 仓库支持 Qt6 的 appstream-qt 就绪

**Comment by BLumia** [comment]
备注：v23 beta3 附带版本（tag 0.4.6）即使用 Qt6。tag 0.5.0 起不再支持 Qt 5。
