### ISSUE TITLE
旧 AM 卸载功能兼容模块的实现与集成

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/developer-center#6025]
```[tasklist]
### Tasks
- [x] 整理代码并推送 dde-application-wizard 兼容模块到仓库
- [ ] https://github.com/linuxdeepin/lastore-daemon/pull/120
- [ ] https://github.com/deepin-community/qcoro/pull/2
- [x] 提测 dde-application-wizard
- [ ] https://github.com/linuxdeepin/developer-center/issues/6066
```
