### ISSUE TITLE
python 3.12 default 集成

### ISSUE THREAD

**Issue by UTsweetyfish** [linuxdeepin/developer-center#9565]
### Package repository address | 软件包仓库地址

```
# python 3.12 default 仓库
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/topics:/py3.12-20240703/testing/ ./
# wireshark, libvirt 附加仓库
deb [trusted=yes]  https://ci.deepin.com/repo/obs/deepin:/CI:/topics:/bcg729/testing/ ./
```

### changelog | 更新信息

见下方 OBS 链接

### test suggestion | 测试建议

影响范围仍较大

### Sphere of influence | 影响范围

https://build.deepin.com/project/monitor/deepin:CI:topics:py3.12-20240703?defaults=0&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&arch_aarch64=1&arch_i386=1&arch_loong64=1&arch_riscv64=1&arch_x86_64=1&repo_testing=1

### ADDITIONAL INFORMATION | 额外补充

```[tasklist]
### Tasks
- [ ] ceph
- [x] cwiid
- [x] dbus-python
- [ ] glade
- [x] gringo
- [x] gst-python1.0
- [x] gstreamer-editing-services1.0
- [x] hplip
- [x] imath
- [x] kig
- [x] ldns
- [x] libapache2-mod-python
- [x] libimobiledevice
- [ ] libpeas
- [x] libplist
- [ ] linux
- [ ] llvm-toolchain-15
- [ ] llvm-toolchain-16
- [ ] llvm-toolchain-17
- [ ] openbabel
- [ ] pam-wrapper
- [ ] postgresql-16
- [ ] python3.11
- [ ] rdma-core
- [x] unbound
- [ ] volume-key
- [ ] vtk9
- [x] xdmf
- [x] alsa-lib
- [x] fontforge
- [x] gdb
- [x] libreoffice
- [x] pyqt5
- [x] python3-defaults
- [x] samba
- [x] talloc
- [x] vim
- [x] 处理 libreoffice 升级
- [x] 处理 libxml2 降级
- [x] 处理 onboard 降级
```

```[tasklist]
### Checklist
- [x] 处理 rb
```

**Comment by babyfengfjx** [comment]
@kobe337  请开展集成验证，如摸底验证无问题，需通知其他同学同步升级使用。

**Comment by kobe337** [comment]
python3-dbus 验证：# DBUS_TOP_SRCDIR=/usr/libexec/installed-tests/dbus-python/python3.12
# DBUS_TOP_BUILDDIR=/usr/libexec/installed-tests/dbus-python/python3.12
# PYTHONPATH=
# PYTHON=/usr/bin/python3.12
# running cross-test (for better diagnostics use mjj29's dbus-test)
dbus-daemon[10837]: [session uid=1000 pid=10837] Connection :1.0 (uid=1000 pid=10841 comm="dbus-monitor") became a monitor.
/usr/libexec/installed-tests/dbus-python/python3.12/test/cross-test-server.py:35: DeprecationWarning: Importing dbus.glib to use the GLib main loop with dbus-python is deprecated.
Instead, use this sequence:

    from dbus.mainloop.glib import DBusGMainLoop

    DBusGMainLoop(set_as_default=True)

  import dbus.glib
INFO:cross-test-server:running...
/usr/libexec/installed-tests/dbus-python/python3.12/test/cross-test-client.py:38: DeprecationWarning: Importing dbus.glib to use the GLib main loop with dbus-python is deprecated.
Instead, use this sequence:

    from dbus.mainloop.glib import DBusGMainLoop

    DBusGMainLoop(set_as_default=True)

  import dbus.glib
INFO:cross-test-client:running...
INFO:cross-test-server:Sum of dbus.Array([dbus.Byte(1), dbus.Byte(2), dbus.Byte(3)], signature=dbus.Signature('y')) is 6
INFO:cross-test-server:Sum of dbus.Array([dbus.Byte(1), dbus.Byte(2), dbus.Byte(3)], signature=dbus.Signature('y')) is 6
INFO:cross-test-server:Sum of dbus.Array([dbus.Byte(1), dbus.Byte(2), dbus.Byte(3)], signature=dbus.Signature('y')) is 6
INFO:cross-test-server:Sum of dbus.Array([dbus.Byte(1), dbus.Byte(2), dbus.Byte(3)], signature=dbus.Signature('y')) is 6
INFO:cross-test-server:Sum of dbus.Array([dbus.Int32(1), dbus.Int32(2), dbus.Int32(3)], signature=dbus.Signature('i')) is 6
INFO:cross-test-server:Sum of dbus.Array([dbus.Int32(1), dbus.Int32(2), dbus.Int32(3)], signature=dbus.Signature('i')) is 6
INFO:cross-test-client:Binding signal handler for Triggered
INFO:cross-test-client:method/signal: Triggering signal
INFO:cross-test-server:method/signal: client wants me to emit Triggered(dbus.UInt64(42)) from dbus.String('/Where/Ever')
INFO:cross-test-server:method/signal: Emitting Triggered(dbus.UInt64(42)) from dbus.String('/Where/Ever')
INFO:cross-test-server:method/signal: Emitted Triggered
INFO:cross-test-server:method/signal: Sent reply for Tests.Trigger()
INFO:cross-test-client:method/signal: Triggered(dbus.UInt64(42)) by dbus.ObjectPath('/Where/Ever')
INFO:cross-test-client:method/signal: Trigger() returned
INFO:cross-test-client:signal/callback: Emitting signal to trigger callback
INFO:cross-test-client:signal/callback: Emitting signal returned
INFO:cross-test-server:signal/callback: Triggered by client (:1.3:/Test): (dbus.UInt16(42),dbus.Double(23.0))
INFO:cross-test-client:signal/callback: Response received (dbus.UInt16(42),dbus.Double(23.0))
INFO:cross-test-client:asking server to Exit
INFO:cross-test-server:signal/callback: Sent Response
INFO:cross-test-server:client wants me to Exit
INFO:cross-test-server:will quit when idle
INFO:cross-test-client:server says it will exit
INFO:cross-test-server:main loop exited.
INFO:cross-test-client:main loop exited.
# test-client exit status: 0
ok 1 - cross-test-client produced some output
ok 2 - cross-test-server produced some output
ok 3 - cross-test client reported no failures
ok 4 - cross-test server reported no untested functions
# waiting for cross-test server to exit
ok 5 - cross-test server: exit status 0
# ==== client log ====
#    org.freedesktop.DBus.Binding.SingleTests.Sum pass
#    org.freedesktop.DBus.Binding.SingleTests.Sum pass
#    org.freedesktop.DBus.Binding.SingleTests.Sum pass
#    org.freedesktop.DBus.Binding.SingleTests.Sum pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.Identity pass
#    org.freedesktop.DBus.Binding.Tests.IdentityByte pass
#    org.freedesktop.DBus.Binding.Tests.IdentityByte pass
#    org.freedesktop.DBus.Binding.Tests.IdentityByte pass
#    org.freedesktop.DBus.Binding.Tests.IdentityBool pass
#    org.freedesktop.DBus.Binding.Tests.IdentityBool pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityDouble pass
#    org.freedesktop.DBus.Binding.Tests.IdentityString pass
#    org.freedesktop.DBus.Binding.Tests.IdentityString pass
#    org.freedesktop.DBus.Binding.Tests.IdentityString pass
#    org.freedesktop.DBus.Binding.Tests.IdentityString pass
#    org.freedesktop.DBus.Binding.Tests.IdentityByte pass
#    org.freedesktop.DBus.Binding.Tests.IdentityBool pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 pass
#    org.freedesktop.DBus.Binding.Tests.IdentityDouble pass
#    org.freedesktop.DBus.Binding.Tests.IdentityArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityByteArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityByteArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityBoolArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityBoolArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64Array pass
#    org.freedesktop.DBus.Binding.Tests.IdentityDoubleArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityDoubleArray pass
#    org.freedesktop.DBus.Binding.Tests.IdentityStringArray pass
#    org.freedesktop.DBus.Binding.Tests.Sum pass
#    org.freedesktop.DBus.Binding.Tests.Sum pass
#    org.freedesktop.DBus.Binding.Tests.InvertMapping pass
#    org.freedesktop.DBus.Binding.Tests.DeStruct pass
#    org.freedesktop.DBus.Binding.Tests.Primitize pass
#    org.freedesktop.DBus.Binding.Tests.Primitize pass
#    org.freedesktop.DBus.Binding.Tests.Primitize pass
#    org.freedesktop.DBus.Binding.Tests.Primitize pass
#    org.freedesktop.DBus.Binding.Tests.Invert pass
#    org.freedesktop.DBus.Binding.Tests.Invert pass
#    org.freedesktop.DBus.Binding.Tests.Invert pass
#    org.freedesktop.DBus.Binding.Tests.Invert pass
#    org.freedesktop.DBus.Binding.Tests.Trigger pass
#    org.freedesktop.DBus.Binding.TestSignals.Trigger pass
# ==== end ====
# ==== server log ====
#    org.freedesktop.DBus.Binding.SingleTests.Sum ok
#    org.freedesktop.DBus.Binding.SingleTests.Sum ok
#    org.freedesktop.DBus.Binding.SingleTests.Sum ok
#    org.freedesktop.DBus.Binding.SingleTests.Sum ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.Identity ok
#    org.freedesktop.DBus.Binding.Tests.IdentityByte ok
#    org.freedesktop.DBus.Binding.Tests.IdentityByte ok
#    org.freedesktop.DBus.Binding.Tests.IdentityByte ok
#    org.freedesktop.DBus.Binding.Tests.IdentityBool ok
#    org.freedesktop.DBus.Binding.Tests.IdentityBool ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityDouble ok
#    org.freedesktop.DBus.Binding.Tests.IdentityString ok
#    org.freedesktop.DBus.Binding.Tests.IdentityString ok
#    org.freedesktop.DBus.Binding.Tests.IdentityString ok
#    org.freedesktop.DBus.Binding.Tests.IdentityString ok
#    org.freedesktop.DBus.Binding.Tests.IdentityByte ok
#    org.freedesktop.DBus.Binding.Tests.IdentityBool ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64 ok
#    org.freedesktop.DBus.Binding.Tests.IdentityDouble ok
#    org.freedesktop.DBus.Binding.Tests.IdentityArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityByteArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityByteArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityBoolArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityBoolArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt16Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt16Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt32Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt32Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityInt64Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityUInt64Array ok
#    org.freedesktop.DBus.Binding.Tests.IdentityDoubleArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityDoubleArray ok
#    org.freedesktop.DBus.Binding.Tests.IdentityStringArray ok
#    org.freedesktop.DBus.Binding.Tests.Sum ok
#    org.freedesktop.DBus.Binding.Tests.Sum ok
#    org.freedesktop.DBus.Binding.Tests.InvertMapping ok
#    org.freedesktop.DBus.Binding.Tests.DeStruct ok
#    org.freedesktop.DBus.Binding.Tests.Primitize ok
#    org.freedesktop.DBus.Binding.Tests.Primitize ok
#    org.freedesktop.DBus.Binding.Tests.Primitize ok
#    org.freedesktop.DBus.Binding.Tests.Primitize ok
#    org.freedesktop.DBus.Binding.Tests.Invert ok
#    org.freedesktop.DBus.Binding.Tests.Invert ok
#    org.freedesktop.DBus.Binding.Tests.Invert ok
#    org.freedesktop.DBus.Binding.Tests.Invert ok
#    org.freedesktop.DBus.Binding.Tests.Trigger ok
#    org.freedesktop.DBus.Binding.TestSignals.Trigger ok
#    org.freedesktop.DBus.Binding.Tests.Exit ok
# ==== end ====
1..5

**Comment by kobe337** [comment]
python3-dbusmock test上游脚本验证通过：
![python3-dbusmock](https://github.com/linuxdeepin/developer-center/assets/17869922/026dbe0f-b762-4e5d-a1b8-da5959450bad)

**Comment by kobe337** [comment]
关联软件包 libglib2.0-tests 上游测试脚本验证通过：
![libglib2 0-tests2](https://github.com/linuxdeepin/developer-center/assets/17869922/5acc9b3d-a85e-4dde-b1b9-d4d94dfa5e04)

**Comment by UTsweetyfish** [comment]
onboard 更新至 1.4.1.1-deepin7。修复了因为未获取GIL而创建Python对象导致的闪退错误。

**Comment by kobe337** [comment]
【环境】：
镜像：Deepin OS-23-20240619094316-1_x86_64
仓库：提测单仓库
内核：Linux deepin-PC 6.6.36-amd64-desktop-hwe #23.01.00.29 SMP PREEMPT_DYNAMIC Tue Jul  2 13:48:43 CST 2024 x86_64 GNU/Linux

【结论】：
测试通过，暂无严重问题及影响, 本次针对python3.12进行验证，经过验证，发现可能存在对应用商店的应用安装造成影响，与研发同事进行沟通，并反馈确认，本次集成建议推送，后续如发现问题，及时反馈修复。
覆盖场景如下：
1、安装校验，版本核对，对提测的软件包与关联包进行验证安装、基本功能使用
2、使用上游提供的test脚本进行执行校验
